platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'appsync_chat_app' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  target 'appsync_chat_appTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'appsync_chat_app-tvOS' do
  # Pods for appsync_chat_app-tvOS

  target 'appsync_chat_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
